# Training parameters for the Unified Training Pipeline
processing_parameters:
  # Sampling frequency (Hz)
  f_sampling: 10000
  # Shift used during segmentation (samples)
  shift: 20
  # Number of samples per segment
  segment_length: 10000
  # Cutoff frequency for FFT (Hz)
  cutoff_freq: 250
  db: True
  # Type of synthetic peak to generate ("gaussian", etc.)
  peak_type: "gaussian"
  # Half-window size around each fault frequency for peak injection
  peak_segment: 5
  # Range for random peak amplitudes during synthetic injection
  amplitude_range: [2.0, 20.0]
  sigma_range: [0.5, 1.5]
  noise_factor: 0.0
  include_negative_peaks: true
  random_peak_position: true
  fault_types_to_use: 
  - inter-turn short circuits
  - rotor bar defect
  loads_to_use: []
  phases_to_use: []
  
training_parameters:
  # Number of epochs for binary classification training
  num_epochs_binary: 10
  # Number of epochs for multiclass classification training
  num_epochs_multi: 10
  initial_lr: 0.001
  patience: 10
  
data_parameters:
  # Batch size for training DataLoader
  batch_size: 128

dataset_parameters:
  # Fraction of segments set aside as the test set
  test_size: 0.3
  # Fraction of the train+validation split that becomes the validation set
  val_size: 0.2
  # Normalization method applied to FFT segments ("min-max" or "z-score")
  normalization_method: "min-max"
  normalization_mode: global
  # Augmentations
  train_dataset_cls: HybridAugFaultDataset
  train_dataset_kwargs:
    # faults_per_window
    K: 2 
    # noisy_normal_per_window
    R: 1
    keep_orig: true
    cache: true