# Training parameters
# engine_1 or engine_2
engineLabel: engine_2
# binary or multiclass
task: "binary"
model: ResNet
test_run: false
comet_online: false
seed: 42
processing_parameters:
  # Sampling frequency (Hz)
  f_sampling: 4098
  # Shift used during segmentation (samples)
  shift: 20
  # Number of samples per segment
  segment_length: 10000
  # Cutoff frequency for FFT (Hz)
  cutoff_freq: 250
  db: True
  # Type of synthetic peak to generate ("gaussian", etc.)
  peak_type: "gaussian"
  # Half-window size in Hz around each fault frequency for peak injection
  peak_segment: 4
  # Range for random peak amplitudes during synthetic injection
  amplitude_range: [0.5, 20.0]
  sigma_range: [0.5, 1.5]
  noise_factor: 0.0
  include_negative_peaks: true
  random_peak_position: true
  fault_types_to_use: 
  # - bearing defect
  - inter-turn short circuits
  - rotor bar defect
  loads_to_use:
  - 0
  - 20
  - 40
  - 60
  - 80
  - 100
  phases_to_use:
  - 1
  - 2
  - 3
model_parameters:
  attention_module: false
  dropout: 0.2
training_parameters:
  # Number of epochs for binary classification training
  num_epochs_binary: 30
  # Number of epochs for multiclass classification training
  num_epochs_multi: 30
  initial_lr: 0.001
  patience: 10
data_parameters:
  # Batch size for training DataLoader
  batch_size: 4096
dataset_parameters:
  batch_size: 4096
  normalization_method: min-max
  normalization_mode: global
  real_fault_train: 0
  test_size: 0.3
  val_size: 0.2
  train_dataset_cls: HybridAugFaultDataset
  train_dataset_kwargs:
    K: 2
    R: 1
    cache: true
    keep_orig: true